server:
    port: 9000

spring:
  application:
    name: Zuul

zuul:
  routes:
    gerar:
      path: /notafiscal/gerar
      serviceId: requisitacalculoimposto
      stripPrefix: false
      sensitiveHeaders: Cookie, Set-Cookie
    listar:
      path: /consultar/**
      serviceId: requisitacalculoimposto
      stripPrefix: false
      sensitiveHeaders: Cookie, Set-Cookie
